let pizzaJson = [
    {id:1, name:'Mussarela', img:'images/mussarela.jpg', price:79.90, sizes:['100g', '530g', '860g'], description:'A clássica que nunca falha! Generosa camada de queijo mussarela derretido, rodelas de tomate fresco e um leve toque de orégano.'},
    {id:2, name:'Calabresa', img:'images/calabresaa.jpg', price:65.00, sizes:['320g', '530g', '860g'], description:'O sabor marcante da autêntica linguiça calabresa fatiada, perfeitamente combinada com cebolas finas, azeitonas pretas e orégano.'},
    {id:3, name:'Quatro Queijos', img:'images/4.jpg', price:60.90, sizes:['320g', '530g', '860g'], description:'Uma sinfonia de sabores: mussarela macia, provolone marcante, parmesão ralado e o toque cremoso do verdadeiro catupiry.'},
    {id:4, name:'Americana', img:'images/pizza4.png', price:60.00, sizes:['320g', '530g', '860g'], description:'Recheio farto e delicioso com presunto, ervilhas frescas, champignon, bacon em cubos e muita mussarela derretida.'},
    {id:5, name:'Marguerita', img:'images/margarita.avif', price:79.90, sizes:['320g', '530g', '860g'],description:'Extremamente recheada, com sabor irresistível, com folhas de marguerita frescas dando um toque e sabor diferenciados'},
    {id:6, name:'Moda da Casa', img:'images/pizza6.png', price:59.99, sizes:['320g', '530g', '860g'], description:'A especialidade do chef! Uma combinação irresistível de presunto, calabresa, ovos cozidos, pimentão, cebola e azeitonas, tudo coberto com mussarela.'},
    {id:7, name:'Doce de Leite com Banana', img:'images/pizzado.jpg', price:69.90, sizes:['320g', '530g', '860g'], description:'Uma explosão de sabores! Massa doce, com bananas e doce de leite, tem coisa melhor?'},
    {id:8, name:'Chocolate', img:'images/pizza7.png', price:69, sizes:['320g', '530g', '860g'], description:'A sobremesa perfeita. Base doce coberta com uma farta camada de chocolate ao leite derretido e confeitos coloridos para a alegria de todos.'}
];